# Generated by Django 5.2.4 on 2025-07-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_businessprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
