# Generated by Django 5.2.4 on 2026-07-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0004_businessprofile_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
    ]
