# Generated by Django 5.2.4 on 2026-07-08 11:34

import user_authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0006_business_whatsappconnection_delete_businessprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappconnection',
            name='verify_token',
            field=models.CharField(default=user_authentication.models.generate_verify_token, max_length=255, unique=True),
        ),
    ]
