# Generated by Django 5.2.4 on 2026-07-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0007_alter_whatsappconnection_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappconnection',
            name='connected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
