# Generated by Django 5.2.4 on 2026-07-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0008_alter_whatsappconnection_connected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconnection',
            name='catalog_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
