# Generated by Django 5.2.4 on 2025-07-23 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_business', '0002_customercontact_updated_at_scheduledmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(help_text='Use variables like {{name}}, {{date}}, {{business_name}} for dynamic content')),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('reminder', 'Reminder'), ('update', 'Update'), ('support', 'Support'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='template_attachments/')),
                ('external_link', models.URLField(blank=True, help_text='Optional link to website or landing page', null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
