# Generated by Django 5.2.4 on 2025-07-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_business', '0004_templatecategory_alter_messagetemplate_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={'ordering': [models.Index(fields=['-created_at'], name='')]},
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='content',
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='placeholders',
            field=models.JSONField(blank=True, help_text='List of placeholder values for the template', null=True),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='template_name',
            field=models.CharField(default=1, help_text='Infobip registered template name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
