# Generated by Django 5.2.4 on 2026-08-02 09:47

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0011_alter_product_price'),
        ('user_business', '0007_notification_content_type_notification_object_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customercontact',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text="Key-value pair custom attributes for template variable interpolation e.g. {'city': 'Kumasi'}"),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_contacts', to='user_authentication.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customercontact',
            name='is_opted_in',
            field=models.BooleanField(db_index=True, default=True, help_text='Explicit consent flag for Meta policy & Ghana Data Protection compliance'),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='name',
            field=models.CharField(blank=True, help_text='Contact full name or display label', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, help_text='Enter phone number in E.164 format (e.g. +233241234567 or 233241234567)', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='tag',
            field=models.JSONField(blank=True, default=list, help_text="List of audience tags e.g. ['VIP', 'Youth Group', 'Donors', 'Wholesale']"),
        ),
        migrations.AddConstraint(
            model_name='customercontact',
            constraint=models.UniqueConstraint(fields=('business', 'phone_number'), name='unique_phone_per_business'),
        ),
        migrations.RemoveField(
            model_name='customercontact',
            name='user',
        ),
    ]
