# Generated by Django 5.2.4 on 2026-08-02 21:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0011_alter_product_price'),
        ('user_business', '0008_alter_customercontact_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Lowercase template identifier required by Meta (e.g. order_update_v1)', max_length=512)),
                ('category', models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('AUTHENTICATION', 'Authentication')], default='UTILITY', max_length=32)),
                ('language', models.CharField(choices=[('en_US', 'English (US)'), ('en_GB', 'English (UK)'), ('fr', 'French'), ('es', 'Spanish')], default='en_US', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAUSED', 'Paused'), ('DISABLED', 'Disabled')], default='DRAFT', max_length=32)),
                ('body_text', models.TextField(help_text='Body content with optional variables like {{1}}, {{2}}')),
                ('header_type', models.CharField(choices=[('NONE', 'None'), ('TEXT', 'Text'), ('IMAGE', 'Image'), ('DOCUMENT', 'Document')], default='NONE', max_length=20)),
                ('header_text', models.CharField(blank=True, max_length=60, null=True)),
                ('footer_text', models.CharField(blank=True, max_length=60, null=True)),
                ('meta_template_id', models.CharField(blank=True, max_length=128, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='user_authentication.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('business', 'name', 'language')},
            },
        ),
    ]
